# Generated by Django 4.0 on 2022-01-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
    ]
